version: "3.5"
services:
  spark-master:
    image: fiziy/spark_cluster_yarn:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "8088:8088"
      - "7077:7077"
      - "4040:4040"
      - "18080:18080"
    networks:
      spark-network:
        ipv4_address: 172.18.0.20
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/run_master.sh"
  spark-worker:
    image: fiziy/spark_cluster_yarn:latest
    depends_on:
      - spark-master
    ports:
      - "7177"
    networks:
      - spark-network
    extra_hosts:
      - "spark-master:172.18.0.20"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/run_worker.sh"
networks:
  spark-network:
    driver: bridge
    name: spark-network
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16